---
cloud_controller_uri: api.vcap.me
service:
  name: filesystem
  version: "1.1"
  supported_versions: ["1.1"]
  version_aliases:
    "current": "1.1"
  description: "Persistent filesystem service"
  plans: ['free']
  default_plan: free
  tags: []
#ip_route: 127.0.0.1
index: 0
token: "0xdeadbeef"
logging:
  level: debug
resque:
  host: localhost
  port: 5454
mbus: nats://localhost:4222
pid: /var/vcap/sys/run/filesystem_service.pid
plan_management:
  plans:
    free:
      lifecycle:
        snapshot:
          quota: 5
        serialization: enable
        job: enable
