---
service_name: filesystem
snapshots_base_dir: /var/vcap/services/
serialization_base_dir: /var/vcap/services/
local_db: sqlite3:/var/vcap/services/filesystem/filesystem_node.db
tmp_dir: /var/vcap/snapshot/tmp/
snapshot_quota: 5
# optional download tuning
serialization:
  max_download_size_mb: 200
  max_download_redirects: 5
# Temp directory to save uploaded file
resque:
  host: localhost
  port: 5454
index: 0
node_id: filesystem_node_free_1
download_url_template: http://dl.vcap.me/serialized/%{service}/%{name}/snapshots/%{snapshot_id}?token=%{token}
logging:
  level: debug
# addtional options
tar_bin: tar
